spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.yaml
    parameters:
      appName: VEHICLE
#    default-schema: vehicle <-- this will try to create a table under the schema name set here
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
#        default_schema: vehicle <-- this tries to query tables under the schema set here
    open-in-view: false
logging:
  level:
    org:
      springframework: debug
